name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle

      - name: Initialize database schema & test data
        working-directory: database
        run: |
          psql postgresql://testuser:testpass@127.0.0.1:5432/testdb -f schema.sql
          psql postgresql://testuser:testpass@127.0.0.1:5432/testdb -f init_test.sql

      - name: Create config.properties
        run: |
          echo "DB_URL=jdbc:postgresql://localhost:5432/testdb" > config.properties
          echo "DB_USER=testuser" >> config.properties
          echo "DB_PASSWORD=testpass" >> config.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile Java
        run: ./gradlew compileJava

      - name: Run tests
        run: ./gradlew test --info
